webtalk_init -webtalk_dir C:/Users/240367/Documents/digital-electronics--1/07-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/driver_7seg_4digits_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 21 14:11:55 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "457f1e36-5cda-4f79-93af-0d6e23010c7d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4d478e47bca449c1b160e6498b0fe512" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       K 875  @ 2.93GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2933 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6692_KB" -context "xsim\\usage"
webtalk_transmit -clientid 169052811 -regid "" -xml C:/Users/240367/Documents/digital-electronics--1/07-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/driver_7seg_4digits_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/240367/Documents/digital-electronics--1/07-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/driver_7seg_4digits_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/240367/Documents/digital-electronics--1/07-display_driver/display_driver/display_driver.sim/sim_1/behav/xsim/xsim.dir/driver_7seg_4digits_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
